---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.3
  creationTimestamp: null
  name: sharesambas.sys.bytetrade.io
spec:
  group: sys.bytetrade.io
  names:
    categories:
      - all
    kind: ShareSamba
    listKind: ShareSambaList
    plural: sharesambas
    shortNames:
      - sharesamba
    singular: sharesamba
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.owner
          name: owner
          type: string
        - jsonPath: .spec.operator
          name: operator
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: creation
          type: date
      name: v1
      schema:
        openAPIV3Schema:
          description: ShareSamba is the Schema for the sharesambas API
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              description: ShareSambaSpec defines the desired state of ShareSamba
              properties:
                operator:
                  type: string
                owner:
                  type: string
                share_ids:
                  type: string
              required:
                - operator
                - owner
                - share_ids
              type: object
            status:
              description: ShareSambaStatus defines the observed state of ShareSamba
              properties:
                state:
                  description:
                    'INSERT ADDITIONAL STATUS FIELD - define observed state
                    of cluster Important: Run "make" to regenerate code after modifying
                    this file'
                  type: string
                updateTime:
                  format: date-time
                  type: string
              required:
                - state
                - updateTime
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
